<?php
require_once __DIR__ . '/includes/session.php';
require_once __DIR__ . '/config/database.php';
notezy_session_start();
if (empty($_SESSION['id'])) { header('Location: index.php'); exit; }
$userId = (int) $_SESSION['id'];
$stmt = $conn->prepare('SELECT note_id, title FROM notes WHERE user_id = ? AND archived = 0 ORDER BY updated_at DESC LIMIT 100');
$stmt->bind_param('i', $userId);
$stmt->execute();
$notes = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Notezy · Sơ đồ tư duy</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
<style>
:root{--purple:#7839a6;--pink:#dc579f;--ink:#3b254a}body{min-height:100vh;color:var(--ink);background:radial-gradient(circle at 8% 6%,#ffe0f2,transparent 30%),linear-gradient(135deg,#faf0ff,#f1e5ff 50%,#ffeaf6);font-family:system-ui,-apple-system,"Segoe UI",sans-serif}.topbar{background:rgba(255,251,255,.92);border-bottom:1px solid #e9c9ee;backdrop-filter:blur(12px)}.shell{max-width:1180px;margin:auto;padding:35px 18px}.glass{background:rgba(255,255,255,.86);border:1px solid #e8cbed;border-radius:22px;box-shadow:0 16px 40px rgba(104,43,124,.12)}.intro{padding:26px}.editor{padding:22px}.gradient{background:linear-gradient(135deg,var(--purple),var(--pink));-webkit-background-clip:text;color:transparent}.btn-dream{border:0;color:#fff;font-weight:700;border-radius:12px;padding:11px 18px;background:linear-gradient(135deg,var(--purple),var(--pink));box-shadow:0 7px 18px rgba(176,66,154,.25)}.form-control,.form-select{border-color:#dfbee7;border-radius:12px}.mindmap{display:grid;grid-template-columns:minmax(190px,.8fr) minmax(0,1.7fr);gap:28px;align-items:center;min-height:420px;padding:28px;position:relative}.topic{background:linear-gradient(135deg,var(--purple),var(--pink));color:#fff;padding:22px;border-radius:22px;text-align:center;font-weight:800;box-shadow:0 12px 26px rgba(135,52,150,.24)}.branches{display:grid;gap:16px;position:relative}.branch{background:#fff;border:1px solid #ead2ef;border-left:5px solid var(--pink);border-radius:16px;padding:16px;position:relative}.branch:before{content:"";position:absolute;left:-34px;top:50%;width:28px;height:2px;background:#c786d1}.branch h3{font-size:1rem;color:var(--purple);font-weight:800}.branch ul{margin:0;padding-left:20px}.summary{background:#fff5fc;border-radius:14px;padding:14px;border:1px solid #f0d4e7}@media(max-width:760px){.mindmap{grid-template-columns:1fr}.branch:before{display:none}}
</style></head><body>
<nav class="topbar py-3"><div class="container d-flex justify-content-between align-items-center"><a href="index_notezy.php" class="text-decoration-none fw-bold" style="color:var(--purple)"><i class="fas fa-layer-group me-2"></i>Notezy</a><a href="index_notezy.php" class="btn btn-sm btn-outline-secondary rounded-pill">Quay lại ghi chú</a></div></nav>
<main class="shell"><section class="glass intro mb-4"><span class="badge rounded-pill bg-light text-dark border mb-2">Notebook-style thinking</span><h1 class="fw-bold mb-2">Tóm tắt văn bản thành <span class="gradient">sơ đồ tư duy</span></h1><p class="text-secondary mb-0">Nhìn nhanh ý chính, việc cần làm và mốc thời gian từ ghi chú của bạn.</p></section>
<section class="glass editor mb-4"><div class="row g-3"><div class="col-lg-4"><label class="form-label fw-bold" for="notePicker">Chọn ghi chú</label><select class="form-select" id="notePicker"><option value="">Hoặc nhập văn bản bên cạnh</option><?php foreach($notes as $note): ?><option value="<?= (int)$note['note_id'] ?>"><?= htmlspecialchars($note['title'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div><div class="col-lg-4"><label class="form-label fw-bold" for="mapTitle">Tên sơ đồ</label><input class="form-control" id="mapTitle" maxlength="120" value="Sơ đồ tư duy" placeholder="Ví dụ: Kế hoạch ôn thi"></div><div class="col-lg-4"><label class="form-label fw-bold" for="sourceText">Văn bản cần tổng hợp</label><textarea class="form-control" id="sourceText" rows="3" placeholder="Dán nội dung học tập, công việc hoặc kế hoạch đi chơi..."></textarea></div></div><div class="d-flex flex-wrap gap-2 align-items-center mt-3"><button class="btn-dream" id="buildMap"><i class="fas fa-brain me-2"></i>Tạo sơ đồ tư duy</button><button class="btn btn-outline-secondary rounded-3" type="button" id="loadNotezyMap"><i class="fas fa-diagram-project me-2"></i>Xem sơ đồ dự án Notezy</button><span id="mapStatus" class="text-secondary small" aria-live="polite"></span></div></section>
<section class="glass"><div id="mapEmpty" class="text-center text-secondary p-5"><i class="fas fa-project-diagram fs-1 mb-3 d-block"></i>Sơ đồ sẽ xuất hiện tại đây.</div><div id="mapResult" hidden><div class="px-4 pt-4"><div id="mapSummary" class="summary"></div></div><div class="mindmap"><div class="topic" id="mapTopic"></div><div class="branches" id="mapBranches"></div></div></div></section></main>
<script>
const esc=v=>String(v??'');
document.getElementById('loadNotezyMap').addEventListener('click',()=>{document.getElementById('notePicker').value='';document.getElementById('mapTitle').value='Dự án Notezy · Sơ đồ hoàn thiện';document.getElementById('sourceText').value='Mục tiêu: xây dựng Notezy là ứng dụng ghi chú phục vụ học tập, công việc và kế hoạch cá nhân. Tài khoản: đăng ký, kích hoạt OTP, đăng nhập, hồ sơ, đổi mật khẩu và tùy chọn người dùng. Ghi chú: xem lưới hoặc danh sách, tạo, tự lưu, đính kèm ảnh tệp, ghim, tìm kiếm, nhãn và lọc. Nâng cao: khóa PIN riêng từng ghi chú, chia sẻ read hoặc editor, cộng tác WebSocket thời gian thực và trạng thái ghi chú đặc biệt. AI: tóm tắt LLM, hỏi đáp tiếng Việt, hiển thị nguồn tham chiếu và sơ đồ tư duy. Thời khóa biểu: ba khung giờ sáng chiều tối, gửi ghi chú vào lịch và báo thức theo giờ Việt Nam. Kiểm thử: responsive điện thoại tablet desktop, PWA offline, Docker Compose, phpMyAdmin và health check. Nộp bài: Rubric.xlsx, source Docker, Readme.txt và video demo 1080p có thành viên.';document.getElementById('mapStatus').textContent='Đã nạp sơ đồ dự án mẫu. Nhấn “Tạo sơ đồ tư duy”.';});
document.getElementById('buildMap').addEventListener('click',async()=>{const status=document.getElementById('mapStatus');status.textContent='Đang phân tích nội dung…';const noteId=Number(document.getElementById('notePicker').value||0);const text=document.getElementById('sourceText').value.trim();const title=document.getElementById('mapTitle').value.trim()||'Sơ đồ tư duy';try{const res=await fetch('api/mindmap.php',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({note_id:noteId,text,title})});const json=await res.json();if(!res.ok||json.status!=='success')throw new Error(json.message||'Không thể tạo sơ đồ');const data=json.data;document.getElementById('mapEmpty').hidden=true;document.getElementById('mapResult').hidden=false;document.getElementById('mapTopic').textContent=data.topic;document.getElementById('mapSummary').textContent=data.summary;const branches=document.getElementById('mapBranches');branches.innerHTML='';data.branches.forEach(branch=>{const card=document.createElement('section');card.className='branch';const heading=document.createElement('h3');heading.textContent=branch.label;const list=document.createElement('ul');branch.items.forEach(item=>{const li=document.createElement('li');li.textContent=item;list.appendChild(li)});card.append(heading,list);branches.appendChild(card)});status.textContent='Đã tạo sơ đồ.'}catch(error){status.textContent=error.message}});
</script></body></html>
